micronaut:
  context-path: /dna-analyzer
  application:
    name: ${APPNAME}
  server:
    port: ${APPPORT}
  router:
    versioning:
      enabled: true
      default-version: 1
      parameter:
        enabled: true
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'

elasticsearch:
  endpoint: ${ENDPOINTELASTIC}

log:
  application:
    name: ${APPNAME}